In [1]:
# # Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
dataset= pd.read_csv('/content/sample_data/main.csv')
print(dataset)

     Gender  Glucose    BP  SkinThickness  ...   BMI  PedigreeFunction  Age  Outcome
0      Male      148  72.0           35.0  ...  33.6             0.627   50        1
1    Female       85  66.0           29.0  ...  26.6             0.351   31        0
2    Female      183  64.0            0.0  ...  23.3             0.672   32        1
3    Female       89  66.0           23.0  ...  28.1             0.167   21        0
4      Male      137   NaN           35.0  ...  43.1             2.288   33        1
..      ...      ...   ...            ...  ...   ...               ...  ...      ...
559    Male       85  74.0            0.0  ...  30.1             0.300   35        0
560    Male      125  76.0            0.0  ...  33.8             0.121   54        1
561    Male      198  66.0           32.0  ...  41.3             0.502   28        1
562    Male       87  68.0           34.0  ...  37.6             0.401   24        0
563    Male       99  60.0           19.0  ...  26.9             

In [6]:
dataset.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 564 entries, 0 to 563
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Gender            564 non-null    object 
 1   Glucose           564 non-null    int64  
 2   BP                548 non-null    float64
 3   SkinThickness     553 non-null    float64
 4   Insulin           552 non-null    float64
 5   BMI               547 non-null    float64
 6   PedigreeFunction  546 non-null    float64
 7   Age               564 non-null    int64  
 8   Outcome           564 non-null    int64  
dtypes: float64(5), int64(3), object(1)
memory usage: 39.8+ KB


In [7]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:,0:7].values
# Extracting dependent variable:
y = dataset.iloc[:,8].values

In [8]:
print(X)


[['Male' 148 72.0 ... 0.0 33.6 0.627]
 ['Female' 85 66.0 ... 0.0 26.6 0.35100000000000003]
 ['Female' 183 64.0 ... 0.0 23.3 0.672]
 ...
 ['Male' 198 66.0 ... 274.0 41.3 0.502]
 ['Male' 87 68.0 ... 77.0 37.6 0.401]
 ['Male' 99 60.0 ... 54.0 26.9 0.49700000000000005]]


Gender  Glucose    BP  SkinThickness  ...   BMI  PedigreeFunction  Age  Outcome
0      Male      148  72.0           35.0  ...  33.6             0.627   50        1
1    Female       85  66.0           29.0  ...  26.6             0.351   31        0
2    Female      183  64.0            0.0  ...  23.3             0.672   32        1
3    Female       89  66.0           23.0  ...  28.1             0.167   21        0
5    Female      116  74.0            0.0  ...  25.6             0.201   30        0
..      ...      ...   ...            ...  ...   ...               ...  ...      ...
559    Male       85  74.0            0.0  ...  30.1             0.300   35        0
560    Male      125  76.0            0.0  ...  33.8             0.121   54        1
561    Male      198  66.0           32.0  ...  41.3             0.502   28        1
562    Male       87  68.0           34.0  ...  37.6             0.401   24        0
563    Male       99  60.0           19.0  ...  26.9             0.497   32        0

[497 rows x 9 columns]

In [10]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
dataset = dataset.dropna()
dataset

Gender  Glucose    BP  SkinThickness  ...   BMI  PedigreeFunction  Age  Outcome
0      Male      148  72.0           35.0  ...  33.6             0.627   50        1
1    Female       85  66.0           29.0  ...  26.6             0.351   31        0
2    Female      183  64.0            0.0  ...  23.3             0.672   32        1
3    Female       89  66.0           23.0  ...  28.1             0.167   21        0
5    Female      116  74.0            0.0  ...  25.6             0.201   30        0
..      ...      ...   ...            ...  ...   ...               ...  ...      ...
559    Male       85  74.0            0.0  ...  30.1             0.300   35        0
560    Male      125  76.0            0.0  ...  33.8             0.121   54        1
561    Male      198  66.0           32.0  ...  41.3             0.502   28        1
562    Male       87  68.0           34.0  ...  37.6             0.401   24        0
563    Male       99  60.0           19.0  ...  26.9             0.497   32        0

[497 rows x 9 columns]

In [17]:

dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 497 entries, 0 to 563
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Gender            497 non-null    object 
 1   Glucose           497 non-null    int64  
 2   BP                497 non-null    float64
 3   SkinThickness     497 non-null    float64
 4   Insulin           497 non-null    float64
 5   BMI               497 non-null    float64
 6   PedigreeFunction  497 non-null    float64
 7   Age               497 non-null    int64  
 8   Outcome           497 non-null    int64  
dtypes: float64(5), int64(3), object(1)
memory usage: 38.8+ KB


In [18]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:,0:7].values
# Extracting dependent variable:
y = dataset.iloc[:,8].values

In [19]:

dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 497 entries, 0 to 563
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Gender            497 non-null    object 
 1   Glucose           497 non-null    int64  
 2   BP                497 non-null    float64
 3   SkinThickness     497 non-null    float64
 4   Insulin           497 non-null    float64
 5   BMI               497 non-null    float64
 6   PedigreeFunction  497 non-null    float64
 7   Age               497 non-null    int64  
 8   Outcome           497 non-null    int64  
dtypes: float64(5), int64(3), object(1)
memory usage: 38.8+ KB


In [22]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [24]:
dataset.isnull().sum()

Gender              0
Glucose             0
BP                  0
SkinThickness       0
Insulin             0
BMI                 0
PedigreeFunction    0
Age                 0
Outcome             0
dtype: int64

In [25]:

from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])



In [26]:

X[:, 1] = labelencoder_X.fit_transform(X[:, 1])

In [27]:
print(X)

[[1 81 72.0 ... 0.0 33.6 0.627]
 [0 19 66.0 ... 0.0 26.6 0.35100000000000003]
 [0 111 64.0 ... 0.0 23.3 0.672]
 ...
 [1 123 66.0 ... 274.0 41.3 0.502]
 [1 21 68.0 ... 77.0 37.6 0.401]
 [1 33 60.0 ... 54.0 26.9 0.49700000000000005]]


In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

In [29]:
print(X_train)

[[1 62 80.0 ... 0.0 31.2 0.703]
 [1 79 70.0 ... 360.0 28.0 0.337]
 [0 79 78.0 ... 0.0 38.5 0.52]
 ...
 [0 43 62.0 ... 129.0 35.8 0.514]
 [1 9 68.0 ... 45.0 29.7 0.293]
 [1 49 72.0 ... 0.0 28.9 0.376]]


In [30]:
print(X_test)

[[1 6 78.0 50.0 45.0 33.2 0.42200000000000004]
 [0 5 70.0 32.0 66.0 25.0 0.187]
 [0 41 68.0 19.0 0.0 26.5 0.165]
 [1 25 64.0 24.0 0.0 29.2 0.192]
 [1 53 0.0 0.0 0.0 19.6 0.8320000000000001]
 [1 119 78.0 0.0 0.0 23.5 0.129]
 [1 39 90.0 0.0 0.0 29.6 0.19699999999999998]
 [0 92 68.0 23.0 132.0 25.5 0.326]
 [1 108 66.0 39.0 0.0 42.0 1.893]
 [0 62 84.0 0.0 0.0 28.0 0.284]
 [0 33 74.0 27.0 0.0 29.0 0.203]
 [0 90 78.0 0.0 0.0 32.9 0.8029999999999999]
 [1 102 78.0 32.0 265.0 46.5 1.159]
 [1 79 70.0 0.0 0.0 37.9 0.33399999999999996]
 [0 40 52.0 0.0 0.0 31.2 0.38]
 [0 29 74.0 21.0 73.0 25.9 0.6729999999999999]
 [0 8 60.0 0.0 0.0 26.8 0.268]
 [0 76 78.0 0.0 0.0 45.0 0.19]
 [1 40 70.0 0.0 0.0 34.2 0.251]
 [0 70 84.0 0.0 0.0 31.2 0.252]
 [0 26 80.0 0.0 0.0 42.2 0.237]
 [0 74 74.0 0.0 0.0 27.6 0.244]
 [1 84 78.0 34.0 171.0 34.2 0.893]
 [1 62 60.0 12.0 231.0 27.5 0.527]
 [0 70 108.0 0.0 0.0 48.8 0.22699999999999998]
 [1 36 52.0 0.0 0.0 25.1 0.078]
 [1 70 70.0 38.0 0.0 33.2 0.17]
 [0 24 80.0 14.0 55.0

In [32]:
print(y_test)

[0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 1 1 1 1 0
 1 0 0 0 1 0 0 0 1 1 1 1 1 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 1 0 1 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 0 1 1 1 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 1 0 0]


In [33]:
print(y_train)

[0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0
 0 1 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 1 0
 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 1 0 1 0
 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 1 1 0 0 1 1 1 1 0 0 1 0 0 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0
 0 1 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 1 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0
 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 1 1 0 1 0 1 1 0 0 1
 0 1 1 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 1 1 0 1 0
 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 0 1 0 0 1 1 1 1
 1 1 0 1 1 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 1 0 1 0 1 0 0 1
 0 1]


In [35]:
from sklearn.svm import SVC
model = SVC()

In [36]:
model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [37]:
# Predicting the Test set results
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0])

In [38]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[70 13]
 [18 24]]


In [39]:
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 82/100

from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 75.20


In [40]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives) 
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 23/30
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.2f' % (precision))

Precision: 0.65


In [41]:
# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 23/23+11
recall = recall_score(y_test, y_pred, average='macro')
print('Recall: %.3f' % (recall))

Recall: 0.707


In [42]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# (2*0.829*0.906)/0.829+0.906
# calculate score
score = f1_score(y_test, y_pred, average='macro')
print('F-Measure: %.3f' % (score*100))

F-Measure: 71.315


In [45]:
import pickle 
print("[INFO] Saving model...")
# Save the trained model as a pickle string. 
saved_model=pickle.dump(model,open('/content/drive/My Drive/nishi_model.pkl', 'wb')) 
# Saving model to disk
 

  


[INFO] Saving model...


In [47]:
# Load the pickled model 
model = pickle.load(open('/content/drive/My Drive/nishi_model.pkl','rb'))  
# Use the loaded pickled model to make predictions 
model.predict(X_test) 

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0])

In [49]:
# save the model to disk
import joblib
filename = '/content/drive/My Drive/nishi_model.sav'
joblib.dump(model, filename)
 
# some time later...
 
# load the model from disk
loaded_model = joblib.load(filename)
result = loaded_model.score(X_test, y_test)
print(result)

0.752


In [50]:
!pip install streamlit

     |████████████████████████████████| 7.8MB 13.7MB/s 
     |████████████████████████████████| 112kB 66.5MB/s 
     |████████████████████████████████| 4.2MB 48.4MB/s 
     |████████████████████████████████| 81kB 2.2MB/s 
     |████████████████████████████████| 174kB 82.0MB/s 
     |████████████████████████████████| 122kB 67.3MB/s 
     |████████████████████████████████| 71kB 9.2MB/s 
  Created wheel for blinker: filename=blinker-1.4-cp37-none-any.whl size=13476 sha256=f4e64a59cf4dba5cb14ae2a2e9385eb929aa69e6fbc316a44e7ce410f3b951b1
  Stored in directory: /root/.cache/pip/wheels/92/a0/00/8690a57883956a301d91cf4ec999cc0b258b01e3f548f86e89
Successfully built blinker
ERROR: ipykernel 6.0.2 has requirement ipython<8.0,>=7.23.1, but you'll have ipython 5.5.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement ipykernel~=4.10, but you'll have ipykernel 6.0.2 which is incompatible.
  Found existing installation: importlib-metadata 4.6.1
    Uninstalling importlib-metadata-4.6.1:


In [51]:

# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [52]:
# Load the pickled model
import pickle
pickle_in = open("/content/drive/My Drive/nishi_model.pkl","rb")
model=pickle.load(pickle_in)

In [75]:
%%writefile app.py
import streamlit as st 
from PIL import Image
import pickle
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
st.set_option('deprecation.showfileUploaderEncoding', False)
# Load the pickled model
model = pickle.load(open('/content/drive/My Drive/nishi_model.pkl', 'rb')) 
# Feature Scaling
dataset = pd.read_csv('/content/drive/My Drive/main.csv')
# Extracting independent variable:
X = dataset.iloc[:, [1,2,3,4,5,6,7]].values
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

def predict_note_authentication(Gender,Glucose,BP,SkinThickness, Insulin, BMI , PedigreeFunction):
  output= model.predict([[Gender,Glucose,BP,SkinThickness, Insulin, BMI , PedigreeFunction]])
  print("heartdisease", output)
  if output==[0]:
    prediction="No Heartdisease"
  else :
    prediction="Heartdisease"
  
  print(prediction)
  return prediction
def main():
    
    html_temp = """
   <div class="" style="background-color:Brown;" >
   <div class="clearfix">           
   <div class="col-md-12">
   <center><p style="font-size:40px;color:black;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center> 
   <center><p style="font-size:30px;color:black;margin-top:10px;">Department of Computer Engineering</p></center> 
   <center><p style="font-size:25px;color:black;margin-top:10px;"Machine Learning Endterm lab Experiment</p></center> 
   </div>
   </div>
   </div>
   """
    st.markdown(html_temp,unsafe_allow_html=True)
    st.header("Heartdisease Predictor")

    Gender = st.number_input('Insert a Gender',0,1)
    Glucose= st.number_input('Insert a 1-4 ')
    BP=st.number_input('Insert a BP reading ')
    SkinThickness = st.number_input('Insert between 100 - 200 ')
    Insulin = st.number_input('Insert between 100 - 400 ')
    BMI = st.number_input('Insert 0 or 1 ')
    PedigreeFunction = st.number_input('Insert  ')

    
   
    resul=""
    if st.button("Predict"):
      result=predict_note_authentication(Gender,Glucose,BP,SkinThickness, Insulin, BMI , PedigreeFunction)
      st.success('Model has predicted {}'.format(result))
      
    if st.button("About"):
      st.subheader("Developed by Nishi Singh")
      st.subheader("Head , Department of Computer Engineering")

if __name__=='__main__':
  main()

Overwriting app.py


In [76]:
!nohup streamlit run  app.py &

nohup: appending output to 'nohup.out'


In [55]:
!pip install pyngrok


     |████████████████████████████████| 747kB 13.9MB/s 
  Created wheel for pyngrok: filename=pyngrok-5.0.5-cp37-none-any.whl size=19262 sha256=5c5464ccdaeb754d5ca0540b1558ef269737dac20f7d8c80e14d4c0aad0240e4
  Stored in directory: /root/.cache/pip/wheels/0c/13/64/5ebbcc22eaf53fdf5766b397c1fb17c83f5775fdccf0ea1b88
Successfully built pyngrok


In [56]:
!ngrok authtoken 1sO8VjMd7JuRjhyolG3kzPT2jZT_ZqPnyoqHxbwFu2oNKpZm

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [77]:
from pyngrok import ngrok
url=ngrok.connect(port='8050')
url


<NgrokTunnel: "http://a6e0701120f4.ngrok.io" -> "http://localhost:80">

In [78]:
 !streamlit run --server.port 80 app.py


  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:80
  External URL: http://34.91.190.143:80

heartdisease [0]
No Heartdisease
  Stopping...
^C
